In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.1152, 0.8129],
        [0.9477, 0.3129]]) 



In [8]:
print(f"Data Type: {x_rand.dtype}")
print(f"Shape: {x_rand.shape}")
print(f"Device: {x_rand.device}")


Data Type: torch.float32
Shape: torch.Size([2, 2])
Device: cpu


In [10]:
print(x_data + x_data)
print()

tensor([[2, 4],
        [6, 8]])



In [11]:
print(x_data * 5)
print()

tensor([[ 5, 10],
        [15, 20]])



In [12]:
result = x_data @ x_data.T
print(result)
print()

tensor([[ 5, 11],
        [11, 25]])



In [13]:
print(x_data[0])
print()

tensor([1, 2])



In [14]:
print(x_data[:, 1])
print()

tensor([2, 4])



In [15]:
print(x_data[1, 1])
print()

tensor(4)



In [ ]:
tensor_4x4 = torch.rand(4, 4)
print("Tensor ban đầu (4, 4):")
print(tensor_4x4)
print()

tensor_16x1 = tensor_4x4.view(16, 1)
print("Tensor sau khi reshape (16, 1):")
print(tensor_16x1)

Phan 2

In [22]:
x = torch.ones(1, requires_grad=True)
print(x)

tensor([1.], requires_grad=True)


In [23]:
y = x + 2
print(y)

tensor([3.], grad_fn=<AddBackward0>)


In [24]:
print(y.grad_fn)

In [25]:
z = y * y * 3
print(z)

tensor([27.], grad_fn=<MulBackward0>)


In [26]:
z.backward()
print(x.grad)

tensor([18.])


Phan 3

In [27]:
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

input_tensor = torch.rand(3, 5)

output = linear_layer(input_tensor)

print("Input Tensor:", input_tensor.shape)
print("Output Tensor:", output.shape)
print("output:", output)

Input Tensor: torch.Size([3, 5])
Output Tensor: torch.Size([3, 2])
output: tensor([[ 0.4522, -0.4049],
        [ 0.3006, -0.7014],
        [ 0.2499, -0.5448]], grad_fn=<AddmmBackward0>)


In [29]:
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

input_indices = torch.LongTensor([1, 5, 0, 8])

embeddings = embedding_layer(input_indices)

print(input_indices.shape)
print("Embeddings shape:", embeddings.shape)
print("Embeddings:", embeddings)

torch.Size([4])
Embeddings shape: torch.Size([4, 3])
Embeddings: tensor([[-0.6913, -0.0457,  0.1365],
        [-0.9567, -0.1891,  0.7758],
        [ 1.5193, -0.7278, -0.6417],
        [-1.3502,  1.5101, -0.9647]], grad_fn=<EmbeddingBackward0>)


In [31]:
import torch
import torch.nn as nn

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()  # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # 1. Lấy embedding: (batch_size, seq_len, embedding_dim)
        embeds = self.embedding(indices)

        # 2. Gộp embedding theo câu (lấy trung bình trên chiều seq_len)
        #    Kết quả: (batch_size, embedding_dim)
        sentence_vec = embeds.mean(dim=1)

        # 3. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(sentence_vec))

        # 4. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output


# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)

# Một câu gồm 4 từ, batch_size = 1
input_data = torch.LongTensor([[1, 2, 5, 9]])

output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")  # Dự kiến: torch.Size([1, 2])


Model output shape: torch.Size([1, 2])
